// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjoahcteuiddikmriegb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqb2FoY3RldWlkZGlrbXJpZWdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4OTExNjYsImV4cCI6MjA2NzQ2NzE2Nn0.Ixu06aand0r2QM84yo49eKEnwVOJf8QnRNm_a0HSUQw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});