// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhmhegxdykknbhlcaceb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpobWhlZ3hkeWtrbmJobGNhY2ViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NDU1MTksImV4cCI6MjA2OTUyMTUxOX0.EY7sf-JTftGR4zVmSbxnzVdDIOG_LgcW3eLJzIiStTw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});